package server

import (
	"cms-go/internal/generator"
	"html/template"
	"io"
	"log"
	"net/http"
	"os"

	"github.com/labstack/echo/v4"
)

type Template struct {
	templates *template.Template
}

func (t *Template) Render(w io.Writer, name string, data interface{}, c echo.Context) error {
	return t.templates.ExecuteTemplate(w, name, data)
}

// NewRenderer builds the Echo renderer used for admin forms and the 404 page.
func NewRenderer() *Template {
	tmpl, err := generator.ParseTemplates()
	if err != nil {
		log.Printf("template parse error: %v", err)
		tmpl = template.New("")
	}

	return &Template{templates: tmpl}
}

// DynamicPage serves the pre-rendered static HTML for a page. Pages are
// (re)generated by generator.GenerateTemplatesFromDB whenever a page, layout,
// or component changes, so this handler never touches the DB or executes
// templates per-request.
func DynamicPage(c echo.Context) error {
	filePath := generator.PageFilePath(c.Request().URL.Path)

	content, err := os.ReadFile(filePath)
	if err != nil {
		return c.Render(http.StatusNotFound, "404.html", nil)
	}

	return c.HTMLBlob(http.StatusOK, content)
}
